# Generated by Django 5.1.6 on 2025-02-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='firtsname',
            new_name='firstname',
        ),
    ]
